### ISSUE TITLE
Daily Nutrition Fragment not working

### ISSUE THREAD

**Issue by dartuso** [awave1/fitness-tracker#31]

**Comment by dartuso** [comment]
need to fix for screenshot lul

**Comment by awave1** [comment]
details?

**Comment by dartuso** [comment]
doesn't get information from nutrituion recording

**Comment by dartuso** [comment]
![screenshot_20181213-211543_apptitude](https://user-images.githubusercontent.com/22248414/49985797-25073380-ff22-11e8-9ff7-69f5520259b0.jpg)
![screenshot_20181213-211548_apptitude](https://user-images.githubusercontent.com/22248414/49985799-26386080-ff22-11e8-9f00-5a39a204267b.jpg)

**Comment by dartuso** [comment]
im guessing error with date thing in sql

**Comment by awave1** [comment]
> 
> 
> im guessing error with date thing in sql

because it's supposed to show stuff from previous day.

**Comment by dartuso** [comment]
would it be more useful to show thing from the current day?

**Comment by awave1** [comment]
yea

**Comment by awave1** [comment]
done did fix it
https://github.com/awave1/fitness-tracker/commit/f8f468622da7e3cacccad5181b293112009a5607

**Comment by dartuso** [comment]
god bless
